# Generated by Django 6.0.7 on 2026-07-28 04:18

import django.core.validators
import django.db.models.deletion
import importlib
from django.conf import settings
from django.db import migrations, models


def seed_quiz_domains(apps, _schema_editor):
    domain_model = apps.get_model("dashboard", "QuizDomainConfig")
    for row in (
        {
            "slug": "english",
            "label": "영어",
            "category_path": "학습/언어/영어",
            "allowed_question_types": ["single_choice"],
            "requires_allowlist": False,
            "sort_order": 10,
        },
        {
            "slug": "japanese",
            "label": "일본어",
            "category_path": "학습/언어/일본어",
            "allowed_question_types": ["single_choice"],
            "requires_allowlist": False,
            "sort_order": 20,
        },
        {
            "slug": "aws_saa",
            "label": "AWS SAA",
            "category_path": "학습/자격증/AWS",
            "allowed_question_types": ["single_choice", "multiple_select"],
            "requires_allowlist": True,
            "sort_order": 30,
        },
    ):
        domain_model.objects.update_or_create(
            slug=row["slug"],
            defaults=row,
        )


def drop_tag_revision_triggers(apps, schema_editor):
    bootstrap = importlib.import_module("dashboard.migrations.0002_bootstrap")
    bootstrap.drop_triggers(apps, schema_editor)


def install_tag_revision_triggers(apps, schema_editor):
    bootstrap = importlib.import_module("dashboard.migrations.0002_bootstrap")
    bootstrap.install_triggers(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_bootstrap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeAsk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('answer', models.TextField()),
                ('insufficient_evidence', models.BooleanField(default=False)),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('feedback', models.CharField(blank=True, choices=[('helpful', '도움됨'), ('unhelpful', '도움 안 됨')], max_length=12)),
                ('feedback_note', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeAskSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=250)),
                ('excerpt', models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('source_url', models.URLField(blank=True, max_length=700)),
            ],
            options={
                'ordering': ['rank', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('helpful', '도움됨'), ('incorrect', '틀림'), ('outdated', '오래됨')], db_index=True, max_length=12)),
                ('comment', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LLMUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('classify', '분류'), ('tagging', '태깅'), ('quiz', '퀴즈'), ('ask', '질문')], db_index=True, max_length=12)),
                ('provider', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('api_calls', models.PositiveIntegerField(default=1)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuizDomainConfig',
            fields=[
                ('slug', models.SlugField(max_length=20, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=80)),
                ('category_path', models.CharField(max_length=400, unique=True)),
                ('allowed_question_types', models.JSONField(default=list)),
                ('requires_allowlist', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'slug'],
            },
        ),
        migrations.RunPython(seed_quiz_domains, migrations.RunPython.noop),
        migrations.AddField(
            model_name='cronjob',
            name='disconnected_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='last_import_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='sync_cursor_ts',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.RunPython(
            drop_tag_revision_triggers,
            install_tag_revision_triggers,
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='review_due_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='verification_note',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='verification_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_knowledge_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='verification_status',
            field=models.CharField(choices=[('unverified', '미검증'), ('verified', '검증됨'), ('stale', '재검토 필요')], db_index=True, default='unverified', max_length=12),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='verified_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='domain',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='domain',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='knowledgeitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('verification_status', 'verified'), _negated=True), ('verified_at__isnull', False), _connector='OR'), name='knowledge_verified_has_timestamp'),
        ),
        migrations.AddField(
            model_name='knowledgeasksource',
            name='ask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='dashboard.knowledgeask'),
        ),
        migrations.AddField(
            model_name='knowledgeasksource',
            name='knowledge_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ask_citations', to='dashboard.knowledgeitem'),
        ),
        migrations.AddField(
            model_name='knowledgefeedback',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_feedback_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgefeedback',
            name='knowledge_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='dashboard.knowledgeitem'),
        ),
        migrations.AddIndex(
            model_name='llmusagerecord',
            index=models.Index(fields=['operation', '-created_at'], name='llm_usage_op_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeasksource',
            constraint=models.UniqueConstraint(fields=('ask', 'rank'), name='unique_ask_source_rank'),
        ),
        migrations.RunPython(
            install_tag_revision_triggers,
            drop_tag_revision_triggers,
        ),
    ]
